name: unit-test

on:
  push:
    branches: 
      - master
      - test-*
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core v5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Setup .NET Core v3
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1
    - name: Setup .NET Core v2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.1
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --verbosity normal
